name = "silence-tools-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "silence-tools-db"
database_id = "2ff71c2a-3a0f-41fb-a680-3c2344ea75a1"

[vars]
FRONTEND_URL = "https://silence-tools.pages.dev"
GOLD_DATA_REPO = "Silencehuliang/silence_tools"

[triggers]
crons = ["0 0 * * *"]
